{% set name = "godale" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9bfd9d984348120f9ed8524731eb639b029d9f55001b1f882485fd7ebf33f3a3

build:
  number: 1
  noarch: python
  script:
    - echo billiard > requirements.txt
    - echo billiard > requirements_test.txt
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
  run:
    - python >={{ python_min }}
    - billiard
    - pytest-runner
test:
  imports:
    - godale
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/godale/
  summary: Debauchery tools for concurrent task execution
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
